# Generated by Django 6.0.2 on 2026-09-10 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_solicitud_documento_respuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='observacion_despacho',
            field=models.TextField(blank=True, default='', help_text='Nota del operador ESS al registrar el despacho (ej. despacho parcial, incidencia). Campo propio: antes de 2026-09 se guardaba por error en observacion_anh, pisando la observación de la ANH.', verbose_name='Observación de despacho'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_combustible',
            field=models.CharField(choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_combustible_aprobado',
            field=models.CharField(blank=True, choices=[('GASOLINA', 'Gasolina'), ('DIESEL', 'Diésel')], max_length=20, null=True),
        ),
    ]
