# Generated by Django 6.0.2 on 2026-09-10 03:31

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models.functions import Lower, Trim


def normalizar_emails_existentes(apps, schema_editor):
    """
    Normaliza los emails a minúsculas ANTES de que esta misma
    migración agregue el UniqueConstraint(Lower("email")) de abajo.
    Si dos cuentas coexistentes solo difirieran en mayúsculas
    (ej. Juan@x.com / juan@x.com), crear el constraint fallaría acá
    con un error de integridad. La auditoría de 2026-09 no encontró
    colisiones en los datos reales (27 usuarios, 3 con mayúsculas,
    0 colisiones al normalizar), pero este paso lo deja seguro para
    cualquier entorno — no depende de correr el management command
    `normalizar_emails` a mano antes de hacer migrate.

    UPDATE en una sola query (Lower+Trim a nivel de base) en vez de
    iterar en Python: más rápido y sin riesgo de saltarse filas.
    """
    User = apps.get_model("users", "User")
    User.objects.update(email=Lower(Trim("email")))


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            normalizar_emails_existentes,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_user_email_lower_unique'),
        ),
    ]
